version: 2.1

commands:
  restore-deps:
    steps:
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}

executors:
  default-node:
    docker:
      - image: circleci/node:8
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"

jobs:
  lint:
    executor: default-node
    steps:
      - checkout
      - restore-deps
      - run: npm run lint

  refresh-deps:
    executor: default-node
    steps:
      - checkout
      - restore-deps
      - run: npm install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    executor: default-node
    steps:
      - checkout
      - restore-deps
      - run: npm run test-codacy

workflows:
  version: 2
  pipeline:
    jobs:
      - lint:
          requires:
            - refresh-deps
      - refresh-deps
      - test:
          requires:
            - refresh-deps
