version: 2.1

commands:
  restore-deps:
    steps:
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

executors:
  default-node:
    docker:
      - image: circleci/node:8.15
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install yq
          command: |
            curl -L -o /usr/bin/yq https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_amd64
            chmod +x /usr/bin/yq
      - run:
          name: Inject environment secrets into app.yaml
          command: |
            yq write --inplace app.yaml env_variables.DIALOGFLOW_PASSWORD ${DIALOGFLOW_PASSWORD}
            yq write --inplace app.yaml env_variables.DIALOGFLOW_USER ${DIALOGFLOW_USER}
      - run:
            name: Authenticate gcloud
            command: |
              echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
            name: Deploy to GAE
            command: |
              VERSION=$(echo "$CIRCLE_SHA1" | cut -c -7)
              gcloud app deploy app.yaml cron.yaml --version="$VERSION"

  lint:
    executor: default-node
    steps:
      - checkout
      - restore-deps
      - run: npm run lint

  refresh-deps:
    executor: default-node
    steps:
      - checkout
      - restore-deps
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    executor: default-node
    steps:
      - checkout
      - restore-deps

workflows:
  version: 2
  pipeline:
    jobs:
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - lint:
          requires:
            - refresh-deps
      - refresh-deps
      - test:
          requires:
            - refresh-deps
